# Binary Classification Problem

In [26]:
# Importing Necessary Libraries

import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

In [5]:
#import csv file

df = pd.read_csv(r'C:\Users\sayanezio\Desktop\binary-classification-competition\train.csv')

In [6]:
df.head() # Show the headers of Dataframe

Unnamed: 0  column_a  column_c  column_d  column_e  column_f  column_g  \
0           0       1.0   0.97714   0.19049   0.82683   0.46259   0.71771   
1           1       1.0   1.00000   0.24077   0.99815   0.00369   0.80244   
2           2       1.0   0.32834   0.02520   0.15236   0.21278   0.14919   
3           3       1.0   0.99645   0.06468   1.00000  -0.01236   0.97811   
4           4       1.0  -0.00641  -0.50000   0.00000   0.00000  -0.01923   

   column_h  column_i  column_j  ...  column_z  column_aa  column_ab  \
0   0.58732   0.47968   0.84278  ...   0.17849   -0.83314   -0.01358   
1  -0.30133   0.89919  -0.23486  ...  -0.52142    0.29208   -0.48390   
2   0.74003  -0.25706   0.92324  ...  -0.06295    0.33737   -0.11876   
3   0.02498   0.96112   0.02312  ...   0.13412    0.79476    0.13638   
4   1.00000   0.00000   0.00000  ...   0.00000   -0.61538   -0.51282   

   column_ac  column_ad  column_ae  column_af  column_ag  column_ah  label  
0   -0.82366   -0.19321   -0.67289   -0.33662   -0.59943   -0.49700      1  
1    0.12777   -0.39143    0.15657   -0.51329    0.18353   -0.46603      1  
2    0.27657   -0.11409    0.15078    0.13296    0.12197    0.20468      1  
3    0.79110    0.15379    0.77122    0.15930    0.70941    0.12015      1  
4    0.00000    0.00000    0.00000    0.00000    0.00000    0.00000      0  

[5 rows x 35 columns]

In [ ]:
# Defining dependent and Independent variable

In [9]:
x = df.drop(['Unnamed: 0','label'], axis = 'columns').values

In [10]:
x

array([[ 1.     ,  0.97714,  0.19049, ..., -0.33662, -0.59943, -0.497  ],
       [ 1.     ,  1.     ,  0.24077, ..., -0.51329,  0.18353, -0.46603],
       [ 1.     ,  0.32834,  0.0252 , ...,  0.13296,  0.12197,  0.20468],
       ...,
       [ 1.     ,  1.     ,  0.5782 , ..., -1.     ,  1.     , -1.     ],
       [ 1.     ,  1.     , -1.     , ...,  1.     ,  1.     ,  1.     ],
       [ 1.     ,  1.     ,  0.11765, ...,  0.35294,  1.     ,  0.23529]])

In [11]:
y = df['label'].values

In [12]:
y


array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1], dtype=int64)

In [13]:
df.describe()

Unnamed: 0    column_a    column_c    column_d    column_e    column_f  \
count  245.000000  245.000000  245.000000  245.000000  245.000000  245.000000   
mean   122.000000    0.881633    0.643574    0.050042    0.580782    0.092967   
std     70.869599    0.323704    0.489701    0.446402    0.534231    0.477736   
min      0.000000    0.000000   -1.000000   -1.000000   -1.000000   -1.000000   
25%     61.000000    1.000000    0.437500   -0.063430    0.386960   -0.044940   
50%    122.000000    1.000000    0.881100    0.008400    0.799170    0.012700   
75%    183.000000    1.000000    1.000000    0.199590    1.000000    0.331430   
max    244.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         column_g    column_h    column_i    column_j  ...    column_z  \
count  245.000000  245.000000  245.000000  245.000000  ...  245.000000   
mean     0.544358    0.103742    0.507047    0.183076  ...   -0.094423   
std      0.494675    0.536860    0.522679    0.505519  ...    0.519309   
min     -1.000000   -1.000000   -1.000000   -1.000000  ...   -1.000000   
25%      0.189190   -0.076530    0.120300   -0.062570  ...   -0.407470   
50%      0.717710    0.003720    0.680650    0.016390  ...   -0.019420   
75%      0.975450    0.433880    0.961120    0.638420  ...    0.133330   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

        column_aa   column_ab   column_ac   column_ad   column_ae   column_af  \
count  245.000000  245.000000  245.000000  245.000000  245.000000  245.000000   
mean     0.521579   -0.088732    0.340606   -0.044347    0.301206   -0.027143   
std      0.544318    0.560603    0.589312    0.506708    0.594110    0.525502   
min     -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   
25%      0.206450   -0.483900    0.000000   -0.277780    0.000000   -0.300570   
50%      0.708860   -0.024510    0.434810    0.000000    0.369240    0.000000   
75%      1.000000    0.143140    0.859770    0.111110    0.829560    0.166670   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

        column_ag   column_ah       label  
count  245.000000  245.000000  245.000000  
mean     0.314007   -0.019470    0.616327  
std      0.543413    0.488015    0.487275  
min     -1.000000   -1.000000    0.000000  
25%      0.000000   -0.244900    0.000000  
50%      0.347490    0.000000    1.000000  
75%      0.790890    0.132970    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 35 columns]

# Fitting the data into model

In [46]:
# Fitting the data into model

model = RandomForestClassifier(n_estimators=1000, random_state=0)

In [18]:
from sklearn.metrics import accuracy_score,classification_report

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0)

In [47]:
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=1000, random_state=0)

# Predicting the model result

In [48]:
y_pred = model.predict(x_test)

In [49]:
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [50]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90        21
           1       0.95      0.95      0.95        41

    accuracy                           0.94        62
   macro avg       0.93      0.93      0.93        62
weighted avg       0.94      0.94      0.94        62



In [53]:
# making confusion matrix

In [56]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [57]:
print(cm)

[[19  2]
 [ 2 39]]
